/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RessourcesIndexRouteImport } from './routes/ressources/index'
import { Route as RessourcesPlanDeCriseRouteImport } from './routes/ressources/plan-de-crise'
import { Route as RessourcesSlugRouteImport } from './routes/ressources/$slug'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthenticatedTimerIndexRouteImport } from './routes/_authenticated/timer/index'
import { Route as AuthenticatedSymptomsIndexRouteImport } from './routes/_authenticated/symptoms/index'
import { Route as AuthenticatedStrengthsIndexRouteImport } from './routes/_authenticated/strengths/index'
import { Route as AuthenticatedRoutinesIndexRouteImport } from './routes/_authenticated/routines/index'
import { Route as AuthenticatedRewardsIndexRouteImport } from './routes/_authenticated/rewards/index'
import { Route as AuthenticatedReportIndexRouteImport } from './routes/_authenticated/report/index'
import { Route as AuthenticatedMedicationsIndexRouteImport } from './routes/_authenticated/medications/index'
import { Route as AuthenticatedJournalIndexRouteImport } from './routes/_authenticated/journal/index'
import { Route as AuthenticatedDecodeurIndexRouteImport } from './routes/_authenticated/decodeur/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCrisisListIndexRouteImport } from './routes/_authenticated/crisis-list/index'
import { Route as AuthenticatedConnaissancesIndexRouteImport } from './routes/_authenticated/connaissances/index'
import { Route as AuthenticatedCarePathwayIndexRouteImport } from './routes/_authenticated/care-pathway/index'
import { Route as AuthenticatedBurnoutIndexRouteImport } from './routes/_authenticated/burnout/index'
import { Route as AuthenticatedBarkleyIndexRouteImport } from './routes/_authenticated/barkley/index'
import { Route as AuthenticatedAdminVaultIndexRouteImport } from './routes/_authenticated/admin-vault/index'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity/index'
import { Route as AuthenticatedAchievementsIndexRouteImport } from './routes/_authenticated/achievements/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedConnaissancesSlugRouteImport } from './routes/_authenticated/connaissances/$slug'
import { Route as AuthenticatedBarkleyFormationStepNumberRouteImport } from './routes/_authenticated/barkley/formation/$stepNumber'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesIndexRoute = RessourcesIndexRouteImport.update({
  id: '/ressources/',
  path: '/ressources/',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesPlanDeCriseRoute = RessourcesPlanDeCriseRouteImport.update({
  id: '/ressources/plan-de-crise',
  path: '/ressources/plan-de-crise',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesSlugRoute = RessourcesSlugRouteImport.update({
  id: '/ressources/$slug',
  path: '/ressources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimerIndexRoute = AuthenticatedTimerIndexRouteImport.update({
  id: '/timer/',
  path: '/timer/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSymptomsIndexRoute =
  AuthenticatedSymptomsIndexRouteImport.update({
    id: '/symptoms/',
    path: '/symptoms/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStrengthsIndexRoute =
  AuthenticatedStrengthsIndexRouteImport.update({
    id: '/strengths/',
    path: '/strengths/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutinesIndexRoute =
  AuthenticatedRoutinesIndexRouteImport.update({
    id: '/routines/',
    path: '/routines/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRewardsIndexRoute =
  AuthenticatedRewardsIndexRouteImport.update({
    id: '/rewards/',
    path: '/rewards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportIndexRoute =
  AuthenticatedReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMedicationsIndexRoute =
  AuthenticatedMedicationsIndexRouteImport.update({
    id: '/medications/',
    path: '/medications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalIndexRoute =
  AuthenticatedJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDecodeurIndexRoute =
  AuthenticatedDecodeurIndexRouteImport.update({
    id: '/decodeur/',
    path: '/decodeur/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrisisListIndexRoute =
  AuthenticatedCrisisListIndexRouteImport.update({
    id: '/crisis-list/',
    path: '/crisis-list/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnaissancesIndexRoute =
  AuthenticatedConnaissancesIndexRouteImport.update({
    id: '/connaissances/',
    path: '/connaissances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarePathwayIndexRoute =
  AuthenticatedCarePathwayIndexRouteImport.update({
    id: '/care-pathway/',
    path: '/care-pathway/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBurnoutIndexRoute =
  AuthenticatedBurnoutIndexRouteImport.update({
    id: '/burnout/',
    path: '/burnout/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBarkleyIndexRoute =
  AuthenticatedBarkleyIndexRouteImport.update({
    id: '/barkley/',
    path: '/barkley/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVaultIndexRoute =
  AuthenticatedAdminVaultIndexRouteImport.update({
    id: '/admin-vault/',
    path: '/admin-vault/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAchievementsIndexRoute =
  AuthenticatedAchievementsIndexRouteImport.update({
    id: '/achievements/',
    path: '/achievements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnaissancesSlugRoute =
  AuthenticatedConnaissancesSlugRouteImport.update({
    id: '/connaissances/$slug',
    path: '/connaissances/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBarkleyFormationStepNumberRoute =
  AuthenticatedBarkleyFormationStepNumberRouteImport.update({
    id: '/barkley/formation/$stepNumber',
    path: '/barkley/formation/$stepNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/ressources/plan-de-crise': typeof RessourcesPlanDeCriseRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/connaissances/$slug': typeof AuthenticatedConnaissancesSlugRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/achievements/': typeof AuthenticatedAchievementsIndexRoute
  '/activity/': typeof AuthenticatedActivityIndexRoute
  '/admin-vault/': typeof AuthenticatedAdminVaultIndexRoute
  '/barkley/': typeof AuthenticatedBarkleyIndexRoute
  '/burnout/': typeof AuthenticatedBurnoutIndexRoute
  '/care-pathway/': typeof AuthenticatedCarePathwayIndexRoute
  '/connaissances/': typeof AuthenticatedConnaissancesIndexRoute
  '/crisis-list/': typeof AuthenticatedCrisisListIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/decodeur/': typeof AuthenticatedDecodeurIndexRoute
  '/journal/': typeof AuthenticatedJournalIndexRoute
  '/medications/': typeof AuthenticatedMedicationsIndexRoute
  '/report/': typeof AuthenticatedReportIndexRoute
  '/rewards/': typeof AuthenticatedRewardsIndexRoute
  '/routines/': typeof AuthenticatedRoutinesIndexRoute
  '/strengths/': typeof AuthenticatedStrengthsIndexRoute
  '/symptoms/': typeof AuthenticatedSymptomsIndexRoute
  '/timer/': typeof AuthenticatedTimerIndexRoute
  '/barkley/formation/$stepNumber': typeof AuthenticatedBarkleyFormationStepNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/ressources/plan-de-crise': typeof RessourcesPlanDeCriseRoute
  '/ressources': typeof RessourcesIndexRoute
  '/connaissances/$slug': typeof AuthenticatedConnaissancesSlugRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/achievements': typeof AuthenticatedAchievementsIndexRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
  '/admin-vault': typeof AuthenticatedAdminVaultIndexRoute
  '/barkley': typeof AuthenticatedBarkleyIndexRoute
  '/burnout': typeof AuthenticatedBurnoutIndexRoute
  '/care-pathway': typeof AuthenticatedCarePathwayIndexRoute
  '/connaissances': typeof AuthenticatedConnaissancesIndexRoute
  '/crisis-list': typeof AuthenticatedCrisisListIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/decodeur': typeof AuthenticatedDecodeurIndexRoute
  '/journal': typeof AuthenticatedJournalIndexRoute
  '/medications': typeof AuthenticatedMedicationsIndexRoute
  '/report': typeof AuthenticatedReportIndexRoute
  '/rewards': typeof AuthenticatedRewardsIndexRoute
  '/routines': typeof AuthenticatedRoutinesIndexRoute
  '/strengths': typeof AuthenticatedStrengthsIndexRoute
  '/symptoms': typeof AuthenticatedSymptomsIndexRoute
  '/timer': typeof AuthenticatedTimerIndexRoute
  '/barkley/formation/$stepNumber': typeof AuthenticatedBarkleyFormationStepNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/ressources/$slug': typeof RessourcesSlugRoute
  '/ressources/plan-de-crise': typeof RessourcesPlanDeCriseRoute
  '/ressources/': typeof RessourcesIndexRoute
  '/_authenticated/connaissances/$slug': typeof AuthenticatedConnaissancesSlugRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/achievements/': typeof AuthenticatedAchievementsIndexRoute
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
  '/_authenticated/admin-vault/': typeof AuthenticatedAdminVaultIndexRoute
  '/_authenticated/barkley/': typeof AuthenticatedBarkleyIndexRoute
  '/_authenticated/burnout/': typeof AuthenticatedBurnoutIndexRoute
  '/_authenticated/care-pathway/': typeof AuthenticatedCarePathwayIndexRoute
  '/_authenticated/connaissances/': typeof AuthenticatedConnaissancesIndexRoute
  '/_authenticated/crisis-list/': typeof AuthenticatedCrisisListIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/decodeur/': typeof AuthenticatedDecodeurIndexRoute
  '/_authenticated/journal/': typeof AuthenticatedJournalIndexRoute
  '/_authenticated/medications/': typeof AuthenticatedMedicationsIndexRoute
  '/_authenticated/report/': typeof AuthenticatedReportIndexRoute
  '/_authenticated/rewards/': typeof AuthenticatedRewardsIndexRoute
  '/_authenticated/routines/': typeof AuthenticatedRoutinesIndexRoute
  '/_authenticated/strengths/': typeof AuthenticatedStrengthsIndexRoute
  '/_authenticated/symptoms/': typeof AuthenticatedSymptomsIndexRoute
  '/_authenticated/timer/': typeof AuthenticatedTimerIndexRoute
  '/_authenticated/barkley/formation/$stepNumber': typeof AuthenticatedBarkleyFormationStepNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/reset-password'
    | '/invite/$token'
    | '/ressources/$slug'
    | '/ressources/plan-de-crise'
    | '/ressources/'
    | '/connaissances/$slug'
    | '/account/'
    | '/achievements/'
    | '/activity/'
    | '/admin-vault/'
    | '/barkley/'
    | '/burnout/'
    | '/care-pathway/'
    | '/connaissances/'
    | '/crisis-list/'
    | '/dashboard/'
    | '/decodeur/'
    | '/journal/'
    | '/medications/'
    | '/report/'
    | '/rewards/'
    | '/routines/'
    | '/strengths/'
    | '/symptoms/'
    | '/timer/'
    | '/barkley/formation/$stepNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialite'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/reset-password'
    | '/invite/$token'
    | '/ressources/$slug'
    | '/ressources/plan-de-crise'
    | '/ressources'
    | '/connaissances/$slug'
    | '/account'
    | '/achievements'
    | '/activity'
    | '/admin-vault'
    | '/barkley'
    | '/burnout'
    | '/care-pathway'
    | '/connaissances'
    | '/crisis-list'
    | '/dashboard'
    | '/decodeur'
    | '/journal'
    | '/medications'
    | '/report'
    | '/rewards'
    | '/routines'
    | '/strengths'
    | '/symptoms'
    | '/timer'
    | '/barkley/formation/$stepNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confidentialite'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/reset-password'
    | '/invite/$token'
    | '/ressources/$slug'
    | '/ressources/plan-de-crise'
    | '/ressources/'
    | '/_authenticated/connaissances/$slug'
    | '/_authenticated/account/'
    | '/_authenticated/achievements/'
    | '/_authenticated/activity/'
    | '/_authenticated/admin-vault/'
    | '/_authenticated/barkley/'
    | '/_authenticated/burnout/'
    | '/_authenticated/care-pathway/'
    | '/_authenticated/connaissances/'
    | '/_authenticated/crisis-list/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/decodeur/'
    | '/_authenticated/journal/'
    | '/_authenticated/medications/'
    | '/_authenticated/report/'
    | '/_authenticated/rewards/'
    | '/_authenticated/routines/'
    | '/_authenticated/strengths/'
    | '/_authenticated/symptoms/'
    | '/_authenticated/timer/'
    | '/_authenticated/barkley/formation/$stepNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RessourcesSlugRoute: typeof RessourcesSlugRoute
  RessourcesPlanDeCriseRoute: typeof RessourcesPlanDeCriseRoute
  RessourcesIndexRoute: typeof RessourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/': {
      id: '/ressources/'
      path: '/ressources'
      fullPath: '/ressources/'
      preLoaderRoute: typeof RessourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/plan-de-crise': {
      id: '/ressources/plan-de-crise'
      path: '/ressources/plan-de-crise'
      fullPath: '/ressources/plan-de-crise'
      preLoaderRoute: typeof RessourcesPlanDeCriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources/$slug': {
      id: '/ressources/$slug'
      path: '/ressources/$slug'
      fullPath: '/ressources/$slug'
      preLoaderRoute: typeof RessourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timer/': {
      id: '/_authenticated/timer/'
      path: '/timer'
      fullPath: '/timer/'
      preLoaderRoute: typeof AuthenticatedTimerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/symptoms/': {
      id: '/_authenticated/symptoms/'
      path: '/symptoms'
      fullPath: '/symptoms/'
      preLoaderRoute: typeof AuthenticatedSymptomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strengths/': {
      id: '/_authenticated/strengths/'
      path: '/strengths'
      fullPath: '/strengths/'
      preLoaderRoute: typeof AuthenticatedStrengthsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routines/': {
      id: '/_authenticated/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof AuthenticatedRoutinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rewards/': {
      id: '/_authenticated/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof AuthenticatedRewardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report/': {
      id: '/_authenticated/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof AuthenticatedReportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medications/': {
      id: '/_authenticated/medications/'
      path: '/medications'
      fullPath: '/medications/'
      preLoaderRoute: typeof AuthenticatedMedicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal/': {
      id: '/_authenticated/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AuthenticatedJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/decodeur/': {
      id: '/_authenticated/decodeur/'
      path: '/decodeur'
      fullPath: '/decodeur/'
      preLoaderRoute: typeof AuthenticatedDecodeurIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crisis-list/': {
      id: '/_authenticated/crisis-list/'
      path: '/crisis-list'
      fullPath: '/crisis-list/'
      preLoaderRoute: typeof AuthenticatedCrisisListIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connaissances/': {
      id: '/_authenticated/connaissances/'
      path: '/connaissances'
      fullPath: '/connaissances/'
      preLoaderRoute: typeof AuthenticatedConnaissancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care-pathway/': {
      id: '/_authenticated/care-pathway/'
      path: '/care-pathway'
      fullPath: '/care-pathway/'
      preLoaderRoute: typeof AuthenticatedCarePathwayIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/burnout/': {
      id: '/_authenticated/burnout/'
      path: '/burnout'
      fullPath: '/burnout/'
      preLoaderRoute: typeof AuthenticatedBurnoutIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barkley/': {
      id: '/_authenticated/barkley/'
      path: '/barkley'
      fullPath: '/barkley/'
      preLoaderRoute: typeof AuthenticatedBarkleyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-vault/': {
      id: '/_authenticated/admin-vault/'
      path: '/admin-vault'
      fullPath: '/admin-vault/'
      preLoaderRoute: typeof AuthenticatedAdminVaultIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements/': {
      id: '/_authenticated/achievements/'
      path: '/achievements'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AuthenticatedAchievementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connaissances/$slug': {
      id: '/_authenticated/connaissances/$slug'
      path: '/connaissances/$slug'
      fullPath: '/connaissances/$slug'
      preLoaderRoute: typeof AuthenticatedConnaissancesSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barkley/formation/$stepNumber': {
      id: '/_authenticated/barkley/formation/$stepNumber'
      path: '/barkley/formation/$stepNumber'
      fullPath: '/barkley/formation/$stepNumber'
      preLoaderRoute: typeof AuthenticatedBarkleyFormationStepNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConnaissancesSlugRoute: typeof AuthenticatedConnaissancesSlugRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAchievementsIndexRoute: typeof AuthenticatedAchievementsIndexRoute
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
  AuthenticatedAdminVaultIndexRoute: typeof AuthenticatedAdminVaultIndexRoute
  AuthenticatedBarkleyIndexRoute: typeof AuthenticatedBarkleyIndexRoute
  AuthenticatedBurnoutIndexRoute: typeof AuthenticatedBurnoutIndexRoute
  AuthenticatedCarePathwayIndexRoute: typeof AuthenticatedCarePathwayIndexRoute
  AuthenticatedConnaissancesIndexRoute: typeof AuthenticatedConnaissancesIndexRoute
  AuthenticatedCrisisListIndexRoute: typeof AuthenticatedCrisisListIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDecodeurIndexRoute: typeof AuthenticatedDecodeurIndexRoute
  AuthenticatedJournalIndexRoute: typeof AuthenticatedJournalIndexRoute
  AuthenticatedMedicationsIndexRoute: typeof AuthenticatedMedicationsIndexRoute
  AuthenticatedReportIndexRoute: typeof AuthenticatedReportIndexRoute
  AuthenticatedRewardsIndexRoute: typeof AuthenticatedRewardsIndexRoute
  AuthenticatedRoutinesIndexRoute: typeof AuthenticatedRoutinesIndexRoute
  AuthenticatedStrengthsIndexRoute: typeof AuthenticatedStrengthsIndexRoute
  AuthenticatedSymptomsIndexRoute: typeof AuthenticatedSymptomsIndexRoute
  AuthenticatedTimerIndexRoute: typeof AuthenticatedTimerIndexRoute
  AuthenticatedBarkleyFormationStepNumberRoute: typeof AuthenticatedBarkleyFormationStepNumberRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConnaissancesSlugRoute: AuthenticatedConnaissancesSlugRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAchievementsIndexRoute: AuthenticatedAchievementsIndexRoute,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
  AuthenticatedAdminVaultIndexRoute: AuthenticatedAdminVaultIndexRoute,
  AuthenticatedBarkleyIndexRoute: AuthenticatedBarkleyIndexRoute,
  AuthenticatedBurnoutIndexRoute: AuthenticatedBurnoutIndexRoute,
  AuthenticatedCarePathwayIndexRoute: AuthenticatedCarePathwayIndexRoute,
  AuthenticatedConnaissancesIndexRoute: AuthenticatedConnaissancesIndexRoute,
  AuthenticatedCrisisListIndexRoute: AuthenticatedCrisisListIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDecodeurIndexRoute: AuthenticatedDecodeurIndexRoute,
  AuthenticatedJournalIndexRoute: AuthenticatedJournalIndexRoute,
  AuthenticatedMedicationsIndexRoute: AuthenticatedMedicationsIndexRoute,
  AuthenticatedReportIndexRoute: AuthenticatedReportIndexRoute,
  AuthenticatedRewardsIndexRoute: AuthenticatedRewardsIndexRoute,
  AuthenticatedRoutinesIndexRoute: AuthenticatedRoutinesIndexRoute,
  AuthenticatedStrengthsIndexRoute: AuthenticatedStrengthsIndexRoute,
  AuthenticatedSymptomsIndexRoute: AuthenticatedSymptomsIndexRoute,
  AuthenticatedTimerIndexRoute: AuthenticatedTimerIndexRoute,
  AuthenticatedBarkleyFormationStepNumberRoute:
    AuthenticatedBarkleyFormationStepNumberRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  RessourcesSlugRoute: RessourcesSlugRoute,
  RessourcesPlanDeCriseRoute: RessourcesPlanDeCriseRoute,
  RessourcesIndexRoute: RessourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
