/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSymptomsIndexRouteImport } from './routes/_authenticated/symptoms/index'
import { Route as AuthenticatedRewardsIndexRouteImport } from './routes/_authenticated/rewards/index'
import { Route as AuthenticatedJournalIndexRouteImport } from './routes/_authenticated/journal/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCrisisListIndexRouteImport } from './routes/_authenticated/crisis-list/index'
import { Route as AuthenticatedBarkleyIndexRouteImport } from './routes/_authenticated/barkley/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'

const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSymptomsIndexRoute =
  AuthenticatedSymptomsIndexRouteImport.update({
    id: '/symptoms/',
    path: '/symptoms/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRewardsIndexRoute =
  AuthenticatedRewardsIndexRouteImport.update({
    id: '/rewards/',
    path: '/rewards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalIndexRoute =
  AuthenticatedJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrisisListIndexRoute =
  AuthenticatedCrisisListIndexRouteImport.update({
    id: '/crisis-list/',
    path: '/crisis-list/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBarkleyIndexRoute =
  AuthenticatedBarkleyIndexRouteImport.update({
    id: '/barkley/',
    path: '/barkley/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/barkley/': typeof AuthenticatedBarkleyIndexRoute
  '/crisis-list/': typeof AuthenticatedCrisisListIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/journal/': typeof AuthenticatedJournalIndexRoute
  '/rewards/': typeof AuthenticatedRewardsIndexRoute
  '/symptoms/': typeof AuthenticatedSymptomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/barkley': typeof AuthenticatedBarkleyIndexRoute
  '/crisis-list': typeof AuthenticatedCrisisListIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/journal': typeof AuthenticatedJournalIndexRoute
  '/rewards': typeof AuthenticatedRewardsIndexRoute
  '/symptoms': typeof AuthenticatedSymptomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/barkley/': typeof AuthenticatedBarkleyIndexRoute
  '/_authenticated/crisis-list/': typeof AuthenticatedCrisisListIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/journal/': typeof AuthenticatedJournalIndexRoute
  '/_authenticated/rewards/': typeof AuthenticatedRewardsIndexRoute
  '/_authenticated/symptoms/': typeof AuthenticatedSymptomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/contact'
    | '/login'
    | '/mentions-legales'
    | '/account/'
    | '/barkley/'
    | '/crisis-list/'
    | '/dashboard/'
    | '/journal/'
    | '/rewards/'
    | '/symptoms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialite'
    | '/contact'
    | '/login'
    | '/mentions-legales'
    | '/account'
    | '/barkley'
    | '/crisis-list'
    | '/dashboard'
    | '/journal'
    | '/rewards'
    | '/symptoms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confidentialite'
    | '/contact'
    | '/login'
    | '/mentions-legales'
    | '/_authenticated/account/'
    | '/_authenticated/barkley/'
    | '/_authenticated/crisis-list/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/journal/'
    | '/_authenticated/rewards/'
    | '/_authenticated/symptoms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/symptoms/': {
      id: '/_authenticated/symptoms/'
      path: '/symptoms'
      fullPath: '/symptoms/'
      preLoaderRoute: typeof AuthenticatedSymptomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rewards/': {
      id: '/_authenticated/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof AuthenticatedRewardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal/': {
      id: '/_authenticated/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AuthenticatedJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crisis-list/': {
      id: '/_authenticated/crisis-list/'
      path: '/crisis-list'
      fullPath: '/crisis-list/'
      preLoaderRoute: typeof AuthenticatedCrisisListIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barkley/': {
      id: '/_authenticated/barkley/'
      path: '/barkley'
      fullPath: '/barkley/'
      preLoaderRoute: typeof AuthenticatedBarkleyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedBarkleyIndexRoute: typeof AuthenticatedBarkleyIndexRoute
  AuthenticatedCrisisListIndexRoute: typeof AuthenticatedCrisisListIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedJournalIndexRoute: typeof AuthenticatedJournalIndexRoute
  AuthenticatedRewardsIndexRoute: typeof AuthenticatedRewardsIndexRoute
  AuthenticatedSymptomsIndexRoute: typeof AuthenticatedSymptomsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedBarkleyIndexRoute: AuthenticatedBarkleyIndexRoute,
  AuthenticatedCrisisListIndexRoute: AuthenticatedCrisisListIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedJournalIndexRoute: AuthenticatedJournalIndexRoute,
  AuthenticatedRewardsIndexRoute: AuthenticatedRewardsIndexRoute,
  AuthenticatedSymptomsIndexRoute: AuthenticatedSymptomsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
